export const API_ENDPOINTS = {
  SIGNUP: '/customer-auth/signup',
  LOGIN: '/customer-auth/login',
  REFRESH_TOKEN: '/customer-auth/refresh-token',
  LOGOUT: '/customer-auth/logout',
  FORGOT_PASSWORD: '/customer-auth/forgot-password',
  RESET_PASSWORD: '/customer-auth/reset-password',
  CHANGE_PASSWORD: '/customer-auth/change-password',
  PROFILE: '/customer',
  CART: '/customer/cart',
  CART_ADD: '/customer/cart/add',
  CART_REMOVE: '/customer/cart/remove',
  ORDERS: '/customer/orders',
  ADDRESSES: '/customer/addresses',
  SLIDES: '/slides',
} as const;
